### ISSUE TITLE
Unable to add Flux Datasource in Grafana V6.0

### ISSUE THREAD

**Issue by ajayanaj** [grafana/influxdb-flux-datasource#34]
What happened: Unable to add Flux datasource in Grafana version 6.0, I'm getting Network Error (500) and Network Error (504). I have an another Grafana instance version 5.4.2, which is working fine as expected.
![image](https://user-images.githubusercontent.com/45065725/56666808-362f3080-66ca-11e9-953c-379642dcc8a2.png)

![image](https://user-images.githubusercontent.com/45065725/56666816-392a2100-66ca-11e9-8420-e2d7ab8fd945.png)

What you expected to happen: It should be added without any errors

How to reproduce it (as minimally and precisely as possible): Add datasource>> Update credentials >> Save and test

Anything else we need to know?:

Environment:

Grafana version: V6.0
Data source type & version: InfluxDB(Flux) datasource and version: 5.2.9
OS Grafana is installed on: Ubuntu 14
User OS & Browser: MAC and Chrome
Grafana plugins:
Others:

**Comment by ajayanaj** [comment]
This is the error i'm seeing in the browser console.

Failed to load resource: the server /api/datasources/proxy/74/api/v2/query:1 Failed to load resource: the server responded with a status of 500 ()
/api/datasources/proxy/83/api/v2/query:1 Failed to load resource: the server responded with a status of 504 ()

**Comment by digrich** [comment]
Similar isssue, not able to load the plugin on 6.2 grafana build.
<img width="1576" alt="Screen Shot 2019-05-09 at 1 28 52 PM" src="https://user-images.githubusercontent.com/9439420/57484732-a14a3c80-725e-11e9-8509-262d2bfb7bf3.png">

**Comment by mqsoh** [comment]
I'm not even able to authenticate the same as the InfluxDB datasource. Using this Docker Compose:

```yaml
version: "3.7"
services:
  grafana:
    image: grafana/grafana:6.2.0
    volumes:
      - ./plugins:/var/lib/grafana/plugins
    ports:
      - "3000:3000"

  myinfluxdb:
    image: influxdb:1.7.5
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_REALM=testing
      - INFLUXDB_ADMIN_USER=testing
      - INFLUXDB_ADMIN_PASSWORD=testing
      - INFLUXDB_DB=testing
      - INFLUXDB_LOGGING_LEVEL=debug
      - HTTP_FLUX_ENABLED=true
```

There's a volume mapping for the plugins directory. So:

```sh
mkdir plugins
cd plugins
# Downloading the latest, 5.2.11
wget https://github.com/grafana/influxdb-flux-datasource/releases/download/5.2.11/influxdb-flux-datasource-5.2.11.zip
unzip influxdb-flux-datasource-5.2.11.zip
```

The InfluxDB datasource works fine.

![image](https://user-images.githubusercontent.com/315803/58206315-70322900-7cae-11e9-8a47-e983e09bac59.png)

But the Flux 5.2.11 datasource doesn't. I'm getting a 403, though, which is different than the other people in this issue.

![image](https://user-images.githubusercontent.com/315803/58206388-92c44200-7cae-11e9-9ffd-87422ec4647e.png)
