### ISSUE TITLE
Provisioning does not work without undocumented fields

### ISSUE THREAD

**Issue by nat45928** [grafana/influxdb-flux-datasource#71]
I was trying to provision a Flux datasource and found I needed to provide a config like:

```
datasources:
  - name: flux
    type: grafana-influxdb-flux-datasource
    url: http://$INFLUXDB_HOST:$INFLUXDB_PORT
    access: proxy
    jsonData:
      bucket: "my_bucket"
      url: http://$INFLUXDB_HOST:$INFLUXDB_PORT
```

The `url` and `access` fields are not well documented.
