### ISSUE TITLE
[Question] how to code datasource.yml to autodeploy a flux datasource ?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/influxdb-flux-datasource#87]
Hello guys. 

I've been looking for documentation but nothing about autodeploy flux datasources.

Here official documentation.

https://grafana.com/docs/grafana/latest/administration/provisioning/

Here a lot of examples for other datasource types

https://raw.githubusercontent.com/grafana/grafana/master/devenv/datasources.yaml

nothing about flux.

Any idea on how to provision flux datasource though the grafana provisioning api?

Thank you very much!

**Comment by toni-moreno** [comment]
Finally I reviewed the browser API queries and these parameters work to me.

```
  - name: flux-datasource-example
    type: grafana-influxdb-flux-datasource
    access: proxy
    basicAuth: true
    basicAuthUser: myuser
    url: http://myinfluxdb:8086
    jsonData:
      timeInterval: "15s"
      bucket: mydb_or_bucket
      url: http://myinfluxdb:8086
    secureJsonData:
      password: sondas
      basicAuthPassword: "mypass"
    secureJsonFields:
      basicAuthPassword: true
    editable: true
```
